version: "3.7"
services:
  app:
    build: .
    # image: amq-streams-kafka-image:latest
    image: event-streams-kafka-image:latest
    ports:
        - 8080:8080/tcp # (if you want single container running)
        # - 8080-8090:8080/tcp # (if you want multiple containers running for multiple producers)